from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
import pandas as pd
from backend.models.schemas import DatasetProfile, PreprocessingPlan, CleaningAction, EDAResults, ReadinessReport

class PreprocessingGraphState(BaseModel):
    session_id: str = Field(..., description='Unique session identifier')
    created_at: str = Field(..., description='Session creation timestamp')
    updated_at: str = Field(..., description='Last update timestamp')
    dataset_path: str = Field(default='', description='Path to the uploaded dataset file')
    file_type: str = Field(default='csv', description='File type: csv, xlsx, json')
    original_dataframe: Optional[Dict[str, Any]] = Field(default=None, description='Serialized original dataframe (stored as dict for JSON serialization)')
    dataset_profile: Optional[DatasetProfile] = Field(default=None, description='Profile information generated by profiling node')
    preprocessing_plan: Optional[PreprocessingPlan] = Field(default=None, description='Preprocessing strategy generated by AI')
    ai_planner_retries: int = Field(default=0, description='Number of retries for AI planner due to malformed responses')
    cleaning_actions: List[CleaningAction] = Field(default_factory=list, description='List of cleaning actions performed')
    cleaned_dataframe: Optional[Dict[str, Any]] = Field(default=None, description='Serialized cleaned dataframe')
    feature_engineering_log: List[Dict[str, Any]] = Field(default_factory=list, description='Log of feature engineering operations')
    processed_dataframe: Optional[Dict[str, Any]] = Field(default=None, description='Serialized processed dataframe after feature engineering')
    encoder_configs: Dict[str, Any] = Field(default_factory=dict, description='Configurations of encoders used for reproducibility')
    scaler_configs: Dict[str, Any] = Field(default_factory=dict, description='Configurations of scalers used for reproducibility')
    eda_results: Optional[EDAResults] = Field(default=None, description='EDA results including plots and statistics')
    readiness_report: Optional[ReadinessReport] = Field(default=None, description='ML readiness validation report')
    generated_files: List[str] = Field(default_factory=list, description='Paths to all generated output files')
    cleaned_dataset_path: str = Field(default='', description='Path to cleaned dataset CSV')
    processed_dataset_path: str = Field(default='', description='Path to processed dataset CSV')
    preprocessing_report_path: str = Field(default='', description='Path to preprocessing report JSON')
    readiness_report_path: str = Field(default='', description='Path to readiness report JSON')
    eda_summary_path: str = Field(default='', description='Path to EDA summary markdown')
    execution_logs: List[str] = Field(default_factory=list, description='Execution log messages from all nodes')
    execution_status: str = Field(default='pending', description='Current execution status: pending, running, completed, failed')
    error_message: Optional[str] = Field(default=None, description='Error message if execution failed')
    processing_start_time: Optional[str] = Field(default=None, description='When processing started')
    processing_end_time: Optional[str] = Field(default=None, description='When processing ended')

    def add_log(self, message: str) -> None:
        self.execution_logs.append(message)

    def add_file(self, file_path: str) -> None:
        if file_path not in self.generated_files:
            self.generated_files.append(file_path)

    def mark_failed(self, error: str) -> None:
        self.execution_status = 'failed'
        self.error_message = error

    class Config:
        arbitrary_types_allowed = True
        json_encoders = {pd.DataFrame: lambda v: v.to_dict(orient='split') if v is not None else None}